### ISSUE TITLE
API DEPRECATED: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 

### ISSUE THREAD

**Issue by songxianpeng** [TrianguloY/mavenDependencyCollapse#5]
IntelliJ IDEA 2024.1 (Ultimate Edition)

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.trianguloy.mavendependencycollapse.CollapseAllAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.trianguloy.mavendependencycollapse]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by TrianguloY** [comment]
fixed on version 1.2.0, currently in review

will close this as soon as it is approved

sorry for the wait
